<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Broiler.JS engine packages for Broiler.JSeal.BroilerJs -->
    <PackageVersion Include="Broiler.JavaScript.BuiltIns" Version="0.1.0-preview.1" />
    <PackageVersion Include="Broiler.JavaScript.Globals" Version="0.1.0-preview.1" />
    <PackageVersion Include="Broiler.JavaScript.Storage" Version="0.1.0-preview.1" />

    <!-- Broiler.VM engine packages for Broiler.JSeal.Vm -->
    <PackageVersion Include="Broiler.VM.Profile.JavaScript" Version="0.1.0-preview.3" />
    <PackageVersion Include="Broiler.VM.Profile.JavaScript.Compiler" Version="0.1.0-preview.3" />
    <PackageVersion Include="Broiler.VM.Runtime" Version="0.1.0-preview.3" />

    <!-- Test dependencies for Broiler.JSeal.Tests -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageVersion Include="xunit" Version="2.5.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>
</Project>
